### ISSUE TITLE
validation

### ISSUE THREAD

**Issue by thungan2011** [thungan2011/inventory-web#22]
Orders: 

- [ ] Edit: Chưa edit được đơn hàng, cập nhật thành công nhưng báo lỗi nhưng thông tin không update. Kiểm tra "địa chỉ" dùm em check rồi mà fix kh ra
- [ ] Tạo đơn hàng: Phần thanh toán có làm thêm cọc tiền hông? 
- [ ] Cập nhật đơn hàng xóa bớt 1 sản phẩm không được

Thành phẩm:

- [x] Thêm trường hợp "cảnh báo tối đa" (Số lượng tồn vượt quá maximun_level); tương tự sửa cho material luôn
- [ ] Có thời gian thì xử lý thêm phần ảnh (Không quan trọng để cuối)

Tồn kho: 

- [x] Cài đặt 3 tháng cảnh báo "Cận date" (Cho cả material và product)
- [x] Nguyên vật liệu: chỗ search theo tên hoặc mã KVLT kh tìm được đã kiểm ra rồi

Nhập kho: 

- [x] Nếu phiếu xuất ở trạng thái "Đã nhập" thì disable nút "Duyệt", "Từ chối"
- [x] Nhập kho > chọn kho > Nhưng  vào kho xem thì kh có nvl chọn để ở kho này

Xuất kho:

- [ ] Xuất kho thành phẩm: hết hạn thì kh được xuất
- [x] Xuất kho thành phẩm: có chọn đơn hàng nhưng xuất không được
- [x] Xuất trả hàng nguyên vật liệu cũng kh được

Nhân viên: 

- [x] Cấp tài khoản nhân viên chưa được

**Comment by Minhquanzz1002** [comment]
- [x] Danh mục
- [x] Bảng giá
